server:
  port: 8080
  ip: 114.132.232.4

spring:
  datasource:
    url: jdbc:mysql://${server.ip}:3306/hotgroup?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: admin@123

redisson:
  lock:
    server:
      address: ${server.ip}:6379
      type: standalone
      password: admin@123
      database: 0

minio:
  endpoint: ${server.ip}:9000
  access-key: admin
  secret-key: admin@1234
  default-bucket: store


logging:
  level:
    com.hotgroup: debug