server:
  port: 8081
  ip: 114.132.232.4

spring:
  datasource:
    url: jdbc:mysql://${server.ip}:3306/hotgroup?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: admin@123

redisson:
  lock:
    server:
      address: ${server.ip}:6379
      type: standalone
      password: admin@123
      database: 0

minio:
  endpoint: ${server.ip}:9000
  access-key: admin
  secret-key: admin@1234
  default-bucket: store


wx:
  miniapp:
    configs:
      - appid: wx395bde5a534e9b9b #微信小程序的appid
        secret: 88dacf11db463fc1335d5dccb204067d #微信小程序的Secret
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON

logging:
  level:
    com.hotgroup: debug
    cn.binarywang.wx.miniapp: debug