server:
  port: 8081
  ip: localhost

spring:
  datasource:
    url: jdbc:mysql://${server.ip}:3306/lead_2021_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: admin@123

redisson:
  lock:
    server:
      address: ${server.ip}:6379
      type: standalone
      password:
      database: 0

minio:
  endpoint: ${server.ip}:9000
  access-key: admin
  secret-key: admin@1234
  default-bucket: store
